"""add_study_rounds

Revision ID: 20260305032434
Revises: 20260304075406
Create Date: 2026-03-05 03:24:36.430448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '20260305032434'
down_revision: Union[str, Sequence[str], None] = '20260304075406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('is_pilot', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('prolific_study_id', sa.String(length=128), nullable=False),
    sa.Column('prolific_study_status', sa.String(length=32), nullable=False),
    sa.Column('places_requested', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('experiments', sa.Column('prolific_description', sa.Text(), nullable=True))
    op.add_column('experiments', sa.Column('prolific_reward', sa.Integer(), nullable=True))
    op.add_column('experiments', sa.Column('prolific_estimated_completion_time', sa.Integer(), nullable=True))
    op.add_column('experiments', sa.Column('prolific_device_compatibility', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'prolific_device_compatibility')
    op.drop_column('experiments', 'prolific_estimated_completion_time')
    op.drop_column('experiments', 'prolific_reward')
    op.drop_column('experiments', 'prolific_description')
    op.drop_table('study_rounds')
    # ### end Alembic commands ###
