"""add_rater_is_preview

Revision ID: faf2ebe67bd9
Revises: 20260304075406
Create Date: 2026-03-05 08:01:30.818161

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "faf2ebe67bd9"
down_revision: Union[str, Sequence[str], None] = "20260304075406"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "raters",
        sa.Column("is_preview", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raters", "is_preview")
    # ### end Alembic commands ###
